//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ledger8.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ledger8.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error.
        /// </summary>
        internal static string DBE {
            get {
                return ResourceManager.GetString("DBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same key has already been added..
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Error.
        /// </summary>
        internal static string IOE {
            get {
                return ResourceManager.GetString("IOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP status code {0} was returned from the server..
        /// </summary>
        internal static string OtherStatus {
            get {
                return ResourceManager.GetString("OtherStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status code was provided..
        /// </summary>
        internal static string Status0 {
            get {
                return ResourceManager.GetString("Status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid request was made..
        /// </summary>
        internal static string Status400 {
            get {
                return ResourceManager.GetString("Status400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated. Please log in..
        /// </summary>
        internal static string Status401 {
            get {
                return ResourceManager.GetString("Status401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform that action..
        /// </summary>
        internal static string Status403 {
            get {
                return ResourceManager.GetString("Status403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page or object was not found..
        /// </summary>
        internal static string Status404 {
            get {
                return ResourceManager.GetString("Status404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect method was used..
        /// </summary>
        internal static string Status405 {
            get {
                return ResourceManager.GetString("Status405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out..
        /// </summary>
        internal static string Status408 {
            get {
                return ResourceManager.GetString("Status408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests have been received from you IP address..
        /// </summary>
        internal static string Status429 {
            get {
                return ResourceManager.GetString("Status429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected server error has occurred..
        /// </summary>
        internal static string Status500 {
            get {
                return ResourceManager.GetString("Status500", resourceCulture);
            }
        }
    }
}
